### ISSUE TITLE
Error installing on Python 3.10

### ISSUE THREAD

**Issue by demberto** [LeftRadio/py-neil-vst-gui#1]
```
Collecting neil-vst>=0.2.7
  Using cached neil_vst-0.2.7.tar.gz (310 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-weijus_4\neil-vst_d8f152744a9a421595b758bfe2db5d95\setup.py", line 16, in <module>
          ext_modules = cythonize( [
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'neil_vst/vst_host.pyx' doesn't match any files
      C:\Users\user\AppData\Local\Temp\pip-install-weijus_4\neil-vst_d8f152744a9a421595b758bfe2db5d95 ['neil_vst']
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by LeftRadio** [comment]
First that the building are tested on python >=3.7 and <=3.9, this is noted in the readme file.
But based on yours error report, cythonize procedure did not find the "vst_host.pyx" file in "py-neil-vst" pypi package from 'neil_vst/vst_host.pyx' relative filepath becouse is your path is 'neil-vst_d8f152744a9a421595b758bfe2db5d95' . Try build the package in virtual environment, for example:

**create and activate the venv:**
>> python -m venv neil-vst-venv
>> cd neil-vst-venv &&  Scripts\activate.bat

**manual install the Cython:**
>> pip install Cython

**build the py-neil-vst-gui:**
>> python -m setup build install

Also please note that you can install this package from pip:
>>python -m pip install neil-vst-gui

**Comment by demberto** [comment]
> Installation requirement python >=3.7

`>=` stands for greater than or equal to.

I think you have left some files untracked.

**Comment by LeftRadio** [comment]
No, all files are tracked. The "py-neil-vst-gui" repo have a sub module - "py-neil-vst" but this sub-module do not cloned by you while you clone the "py-neil-vst-gui" itself. Please use the "--recursive" or "--recurse-submodules" flags, like that:

git clone --recurse-submodules https://github.com/LeftRadio/py-neil-vst-gui

**Comment by demberto** [comment]
I don't think you understand the way submodules work. If you had one really, it would be visible as a link to another repo on Github. To prove myself, I clone your repo with

```
git clone --recurse-submodules https://github.com/LeftRadio/py-neil-vst-gui
```

This is the file tree it created:
```
PY-NEIL-VST-GUI
│   LICENSE
│   README.md
│   setup.py
│
├───img
│       0_1.png
│       0_2.png
│       0_3.png
│       1.png
│       1_1.png
│       2.png
│
└───neil_vst_gui
    │   job.py
    │   main.py
    │   main.qrc
    │   main.ui
    │   main_worker.py
    │   play_chain.py
    │   rects_animate.py
    │   resources.py
    │   tag_write.py
    │   ui_logging.py
    │   ui_settings.json
    │   ui_settings.py
    │   _job.json
    │   __init__.py
    │
    └───res
            all_btn.png
            background_text2.jpg
            start_btn.png
            stop_btn.png
            Untitled_000000.png
```

**Comment by LeftRadio** [comment]
Sorry, this is a my mistake with link the sub-module to this repo. Fix this are soon as posible.
For now you may manualy install the sub-module (base package with CLI) from this repo:
https://github.com/LeftRadio/py-neil-vst
